# Generated by Django 2.2.16 on 2020-10-11 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furigana', models.CharField(blank=True, max_length=50, null=True, verbose_name='フリガナ')),
                ('tel', models.CharField(blank=True, max_length=100, null=True, verbose_name='電話番号')),
                ('adress', models.CharField(blank=True, max_length=100, null=True, verbose_name='住所')),
                ('description', models.TextField(blank=True, default='', verbose_name='備考欄')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='来店日')),
                ('account_core', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='アカウント')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furigana', models.CharField(blank=True, max_length=50, null=True, verbose_name='フリガナ')),
                ('position', models.CharField(blank=True, max_length=30, verbose_name='役職')),
                ('description', models.TextField(blank=True, default='', verbose_name='自己紹介')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='プロフィール画像')),
                ('tel', models.CharField(blank=True, max_length=100, null=True, verbose_name='電話番号')),
                ('adress', models.CharField(blank=True, max_length=100, null=True, verbose_name='住所')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='勤務開始日')),
                ('account_core', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='アカウント')),
            ],
        ),
    ]
