# Generated by Django 2.2.16 on 2020-10-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='サロン名'),
        ),
        migrations.AddField(
            model_name='salon',
            name='sub',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='サブタイトル'),
        ),
    ]
