# Generated by Django 2.2.16 on 2020-10-11 05:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='adress',
        ),
        migrations.AddField(
            model_name='staff',
            name='adress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='staff',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='勤務開始日'),
        ),
        migrations.AddField(
            model_name='staff',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='自己紹介'),
        ),
        migrations.AddField(
            model_name='staff',
            name='furigana',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='フリガナ'),
        ),
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='プロフィール画像'),
        ),
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.CharField(blank=True, max_length=30, verbose_name='役職'),
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='来店日'),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='備考欄'),
        ),
        migrations.AddField(
            model_name='user',
            name='furigana',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='フリガナ'),
        ),
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='電話番号'),
        ),
    ]
