# Generated by Django 2.2.16 on 2020-10-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201022_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='concept1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='コンセプト１'),
        ),
        migrations.AddField(
            model_name='salon',
            name='concept2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='コンセプト２'),
        ),
    ]
