# Generated by Django 2.2.16 on 2020-10-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_menu_menucategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
