# Generated by Django 2.2.16 on 2020-10-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201011_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
