# Generated by Django 2.2.16 on 2020-10-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_menu_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(blank=True, max_length=200, null=True, verbose_name='メールアドレス')),
                ('tel', models.CharField(blank=True, max_length=200, null=True, verbose_name='電話番号')),
                ('opening', models.CharField(blank=True, max_length=30, null=True, verbose_name='開店時間')),
                ('closed', models.CharField(blank=True, max_length=30, null=True, verbose_name='閉店時間')),
                ('regular_holiday', models.CharField(blank=True, max_length=100, null=True, verbose_name='定休日')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='住所')),
                ('access', models.TextField(blank=True, default='', verbose_name='アクセス')),
            ],
        ),
    ]
