# Generated by Django 2.2.16 on 2020-10-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='名前'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='名前'),
            preserve_default=False,
        ),
    ]
