# Generated by Django 2.2.16 on 2020-10-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201013_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[(1, '指定なし'), (2, '男性'), (3, '女性')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[(1, '指定なし'), (2, '男性'), (3, '女性')], default=1, max_length=2),
        ),
    ]
