# Generated by Django 2.2.16 on 2020-10-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0002_auto_20201025_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='ec/static/img/'),
        ),
    ]
