# Generated by Django 2.2.16 on 2020-10-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0003_auto_20201025_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
