# Generated by Django 2.2.16 on 2020-10-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0004_auto_20201025_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='app/static/img/'),
        ),
    ]
