# Generated by Django 2.2.16 on 2020-10-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0005_auto_20201026_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
