# Generated by Django 2.2.16 on 2020-10-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0006_auto_20201026_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='ec'),
        ),
    ]
