# Generated by Django 2.2.16 on 2020-10-12 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0007_menu_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stylist_staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Staff', verbose_name='スタイリスト')),
            ],
        ),
    ]
