# Generated by Django 2.2.16 on 2021-02-20 20:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Staff', verbose_name='スタイリスト')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='名前')),
                ('furigana', models.CharField(blank=True, max_length=50, null=True, verbose_name='フリガナ')),
                ('tel', models.CharField(blank=True, max_length=30, null=True, verbose_name='電話番号')),
                ('remarks', models.TextField(blank=True, default='ご要望などをお書きください', verbose_name='備考')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始時間')),
                ('end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='終了時間')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Staff', verbose_name='スタイリスト')),
            ],
        ),
    ]
