# Generated by Django 2.2.16 on 2020-10-12 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
