# Generated by Django 2.2.16 on 2020-10-13 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20201013_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stylist',
            old_name='stylist',
            new_name='detail',
        ),
    ]
