# Generated by Django 2.2.16 on 2020-10-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20201013_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='stylist',
            new_name='staff',
        ),
    ]
